[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "wavefoam"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19.0", features = ["derive"], optional = true }

[features]
bytemuck = ["dep:bytemuck"]
